version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/WellKnownDataTypes/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/WellKnownDataTypes-Tests/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5